### ISSUE TITLE
`convolution` fails for `Mod1000000007`

### ISSUE THREAD

**Issue by tamuhey** [rust-lang-ja/ac-library-rs#94]
The following test fails: 

```
    #[test]
    fn mid1000000007() {
        const N: usize = 1234;
        const M: usize = 2345;

        let mut rng = rand::thread_rng();
        let mut gen_values = |n| gen_values::<Mod1000000007>(&mut rng, n);
        let (a, b) = (gen_values(N), gen_values(M));
        assert_eq!(conv_naive(&a, &b), super::convolution(&a, &b));
    }
```

Is this a bug?

**Comment by TonalidadeHidrica** [comment]
For mathematical reason, it is impossible to do (practical) convolution on mod 1000000007.  Convolution on mod 998244353 is possible because there exists an integer `x` such that `x^(2^23) == 1 (mod 998244353)`.  Also refer to [this article](https://qiita.com/Sen_comp/items/9401382df736e51564c1#1097%E3%81%A8998244353%E3%81%AE%E9%81%95%E3%81%84) if you speak Japanese.
